<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net8.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<OutputType>Library</OutputType>
		<RootNamespace>PowerApps.Modules</RootNamespace>
		<AssemblyName>PowerApps.Modules.G9</AssemblyName>
	</PropertyGroup>



	<PropertyGroup Condition="'$(Configuration)'=='Debug'">
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
		<DebugType>none</DebugType>
	</PropertyGroup>

	<ItemGroup>
	  <ProjectReference Include="..\..\Shared\DataList\DataList.csproj" />
	  <ProjectReference Include="..\..\Shared\Routing\Routing.csproj" />
	</ItemGroup>
</Project>
